# Generated by Django 4.2 on 2026-02-01 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checkin_time', models.TimeField(blank=True, null=True)),
                ('checkout_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('capacity', models.IntegerField(default=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('customer_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('customer_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('priority', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='delivery.agent')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='delivery.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assignment_date', models.DateField()),
                ('distance_from_warehouse', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_delivery_time', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.order')),
            ],
        ),
        migrations.CreateModel(
            name='AgentDailyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_distance', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_working_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('orders_assigned', models.IntegerField(default=0)),
                ('orders_delivered', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='delivery.agent')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='delivery.warehouse'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_date'], name='delivery_or_status_560de7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['warehouse', 'status'], name='delivery_or_warehou_3c4f46_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_to', 'delivery_date'], name='delivery_or_assigne_04f72f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentlog',
            index=models.Index(fields=['assignment_date', 'agent'], name='delivery_as_assignm_c1996d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentlog',
            unique_together={('agent', 'order', 'assignment_date')},
        ),
        migrations.AddIndex(
            model_name='agentdailymetrics',
            index=models.Index(fields=['date', 'is_active'], name='delivery_ag_date_e4d50c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='agentdailymetrics',
            unique_together={('agent', 'date')},
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['warehouse'], name='delivery_ag_warehou_3d298b_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['is_active'], name='delivery_ag_is_acti_760109_idx'),
        ),
    ]
