# Generated by Django 4.2 on 2026-02-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(default=1)),
                ('attempted_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('successful', 'Successful'), ('failed', 'Failed'), ('rescheduled', 'Rescheduled')], default='failed', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('photo_url', models.URLField(blank=True)),
                ('signature_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='delivery.agent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='delivery.order')),
            ],
            options={
                'ordering': ['attempt_number'],
            },
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['order', 'attempt_number'], name='delivery_de_order_i_5a8786_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['attempted_at'], name='delivery_de_attempt_72d5fb_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryattempt',
            index=models.Index(fields=['agent', 'attempted_at'], name='delivery_de_agent_i_0fcf4e_idx'),
        ),
    ]
