# Generated by Django 4.2 on 2026-02-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.AlterField(
            model_name='deliveryattempt',
            name='attempted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
